version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - package.json
    - package-lock.json
    - server.js
    - node_modules/**/*
    - .env
  base-directory: 'backend'