branch-defaults:
  default:
    environment: contact-system-env
    group_suffix: null
environment-defaults:
  contact-system-env:
    branch: null
    repository: null
global:
  application_name: contact-system-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
